### ISSUE TITLE
Grafana Dashboard template request

### ISSUE THREAD

**Issue by abhay40711cs** [RuntimeTools/appmetrics-prometheus#5]
This is rather an enhancement request 
If possible to have comparable grafana dashboard as it is there in app metric dash.
I believe this can be implemented once we have following metrics in place for  Prometheus 

1. HTTP_RequestTime_second  with labels (route, response code)
2. HTTP_Request_Total
3. HTTP_Request_sum
2. Event Loop latency _ms
3. GC Collection

**Comment by tobespc** [comment]
@abhay40711cs  is this a dashboard for prometheus data ?

**Comment by abhay40711cs** [comment]
Yes, This to collect the metrics and to have it view on customized queries
of Prometheus on grafana such that they are mapping with existing
app-metric dashboard

**Comment by tobespc** [comment]
ok, that would be out of the scope of this project as this is for supplying data to Prometheus rather than doing any data displaying.  We don't have any plans to add any data displaying to appmetrics-prometheus
